// Extended:
//
// HPB bot - botman's High Ping Bastard bot
//
// (http://planethalflife.com/botman/)
//
// linkfunc.cpp
//

#include "extdll.h"
#include "bot.h"


extern HINSTANCE h_Library;


#define LINK_ENTITY_TO_FUNC( mapClassName, mapClassString )			\
																	\
	extern "C" EXPORT void mapClassName( entvars_t *pev );			\
																	\
	void mapClassName( entvars_t *pev )								\
	{																\
		static LINK_ENTITY_FUNC otherClassName = NULL;				\
		static int skip_this = 0;									\
		if (skip_this) return;										\
		if (!otherClassName) otherClassName = (LINK_ENTITY_FUNC)GetProcAddress( h_Library, mapClassString ); \
		if (!otherClassName) {  skip_this = 1;   return;  }			\
		(*otherClassName)( pev );									\
	}



// entities for Valve's hl.dll and Standard SDK...
LINK_ENTITY_TO_FUNC(aiscripted_sequence, "aiscripted_sequence");
LINK_ENTITY_TO_FUNC(ambient_generic, "ambient_generic");
LINK_ENTITY_TO_FUNC(ammo_357, "ammo_357");
LINK_ENTITY_TO_FUNC(ammo_9mmAR, "ammo_9mmAR");
LINK_ENTITY_TO_FUNC(ammo_9mmbox, "ammo_9mmbox");
LINK_ENTITY_TO_FUNC(ammo_9mmclip, "ammo_9mmclip");
LINK_ENTITY_TO_FUNC(ammo_ARgrenades, "ammo_ARgrenades");
LINK_ENTITY_TO_FUNC(ammo_buckshot, "ammo_buckshot");
LINK_ENTITY_TO_FUNC(ammo_crossbow, "ammo_crossbow");
LINK_ENTITY_TO_FUNC(ammo_egonclip, "ammo_egonclip");
LINK_ENTITY_TO_FUNC(ammo_gaussclip, "ammo_gaussclip");
LINK_ENTITY_TO_FUNC(ammo_glockclip, "ammo_glockclip");
LINK_ENTITY_TO_FUNC(ammo_mp5clip, "ammo_mp5clip");
LINK_ENTITY_TO_FUNC(ammo_mp5grenades, "ammo_mp5grenades");
LINK_ENTITY_TO_FUNC(ammo_rpgclip, "ammo_rpgclip");
LINK_ENTITY_TO_FUNC(beam, "beam");
LINK_ENTITY_TO_FUNC(bmortar, "bmortar");
LINK_ENTITY_TO_FUNC(bodyque, "bodyque");
LINK_ENTITY_TO_FUNC(button_target, "button_target");
LINK_ENTITY_TO_FUNC(cine_blood, "cine_blood");
LINK_ENTITY_TO_FUNC(controller_energy_ball, "controller_energy_ball");
LINK_ENTITY_TO_FUNC(controller_head_ball, "controller_head_ball");
LINK_ENTITY_TO_FUNC(crossbow_bolt, "crossbow_bolt");
LINK_ENTITY_TO_FUNC(cycler, "cycler");
LINK_ENTITY_TO_FUNC(cycler_prdroid, "cycler_prdroid");
LINK_ENTITY_TO_FUNC(cycler_sprite, "cycler_sprite");
LINK_ENTITY_TO_FUNC(cycler_weapon, "cycler_weapon");
LINK_ENTITY_TO_FUNC(cycler_wreckage, "cycler_wreckage");
LINK_ENTITY_TO_FUNC(DelayedUse, "DelayedUse");
LINK_ENTITY_TO_FUNC(env_beam, "env_beam");
LINK_ENTITY_TO_FUNC(env_beverage, "env_beverage");
LINK_ENTITY_TO_FUNC(env_blood, "env_blood");
LINK_ENTITY_TO_FUNC(env_bubbles, "env_bubbles");
LINK_ENTITY_TO_FUNC(env_debris, "env_debris");
LINK_ENTITY_TO_FUNC(env_explosion, "env_explosion");
LINK_ENTITY_TO_FUNC(env_fade, "env_fade");
LINK_ENTITY_TO_FUNC(env_funnel, "env_funnel");
LINK_ENTITY_TO_FUNC(env_global, "env_global");
LINK_ENTITY_TO_FUNC(env_glow, "env_glow");
LINK_ENTITY_TO_FUNC(env_laser, "env_laser");
LINK_ENTITY_TO_FUNC(env_lightning, "env_lightning");
LINK_ENTITY_TO_FUNC(env_message, "env_message");
LINK_ENTITY_TO_FUNC(env_render, "env_render");
LINK_ENTITY_TO_FUNC(env_shake, "env_shake");
LINK_ENTITY_TO_FUNC(env_shooter, "env_shooter");
LINK_ENTITY_TO_FUNC(env_smoker, "env_smoker");
LINK_ENTITY_TO_FUNC(env_sound, "env_sound");
LINK_ENTITY_TO_FUNC(env_spark, "env_spark");
LINK_ENTITY_TO_FUNC(env_sprite, "env_sprite");
LINK_ENTITY_TO_FUNC(fireanddie, "fireanddie");
LINK_ENTITY_TO_FUNC(func_breakable, "func_breakable");
LINK_ENTITY_TO_FUNC(func_button, "func_button");
LINK_ENTITY_TO_FUNC(func_conveyor, "func_conveyor");
LINK_ENTITY_TO_FUNC(func_door, "func_door");
LINK_ENTITY_TO_FUNC(func_door_rotating, "func_door_rotating");
LINK_ENTITY_TO_FUNC(func_friction, "func_friction");
LINK_ENTITY_TO_FUNC(func_guntarget, "func_guntarget");
LINK_ENTITY_TO_FUNC(func_healthcharger, "func_healthcharger");
LINK_ENTITY_TO_FUNC(func_illusionary, "func_illusionary");
LINK_ENTITY_TO_FUNC(func_ladder, "func_ladder");
LINK_ENTITY_TO_FUNC(func_monsterclip, "func_monsterclip");
LINK_ENTITY_TO_FUNC(func_mortar_field, "func_mortar_field");
LINK_ENTITY_TO_FUNC(func_pendulum, "func_pendulum");
LINK_ENTITY_TO_FUNC(func_plat, "func_plat");
LINK_ENTITY_TO_FUNC(func_platrot, "func_platrot");
LINK_ENTITY_TO_FUNC(func_pushable, "func_pushable");
LINK_ENTITY_TO_FUNC(func_recharge, "func_recharge");
LINK_ENTITY_TO_FUNC(func_rot_button, "func_rot_button");
LINK_ENTITY_TO_FUNC(func_rotating, "func_rotating");
LINK_ENTITY_TO_FUNC(func_tank, "func_tank");
LINK_ENTITY_TO_FUNC(func_tankcontrols, "func_tankcontrols");
LINK_ENTITY_TO_FUNC(func_tanklaser, "func_tanklaser");
LINK_ENTITY_TO_FUNC(func_tankmortar, "func_tankmortar");
LINK_ENTITY_TO_FUNC(func_tankrocket, "func_tankrocket");
LINK_ENTITY_TO_FUNC(func_trackautochange, "func_trackautochange");
LINK_ENTITY_TO_FUNC(func_trackchange, "func_trackchange");
LINK_ENTITY_TO_FUNC(func_tracktrain, "func_tracktrain");
LINK_ENTITY_TO_FUNC(func_train, "func_train");
LINK_ENTITY_TO_FUNC(func_traincontrols, "func_traincontrols");
LINK_ENTITY_TO_FUNC(func_wall, "func_wall");
LINK_ENTITY_TO_FUNC(func_wall_toggle, "func_wall_toggle");
LINK_ENTITY_TO_FUNC(func_water, "func_water");
LINK_ENTITY_TO_FUNC(game_counter, "game_counter");
LINK_ENTITY_TO_FUNC(game_counter_set, "game_counter_set");
LINK_ENTITY_TO_FUNC(game_end, "game_end");
LINK_ENTITY_TO_FUNC(game_player_equip, "game_player_equip");
LINK_ENTITY_TO_FUNC(game_player_hurt, "game_player_hurt");
LINK_ENTITY_TO_FUNC(game_player_team, "game_player_team");
LINK_ENTITY_TO_FUNC(game_score, "game_score");
LINK_ENTITY_TO_FUNC(game_team_master, "game_team_master");
LINK_ENTITY_TO_FUNC(game_team_set, "game_team_set");
LINK_ENTITY_TO_FUNC(game_text, "game_text");
LINK_ENTITY_TO_FUNC(game_zone_player, "game_zone_player");
LINK_ENTITY_TO_FUNC(garg_stomp, "garg_stomp");
LINK_ENTITY_TO_FUNC(gibshooter, "gibshooter");
LINK_ENTITY_TO_FUNC(grenade, "grenade");
LINK_ENTITY_TO_FUNC(hornet, "hornet");
LINK_ENTITY_TO_FUNC(hvr_rocket, "hvr_rocket");
LINK_ENTITY_TO_FUNC(info_bigmomma, "info_bigmomma");
LINK_ENTITY_TO_FUNC(info_intermission, "info_intermission");
LINK_ENTITY_TO_FUNC(info_landmark, "info_landmark");
LINK_ENTITY_TO_FUNC(info_node, "info_node");
LINK_ENTITY_TO_FUNC(info_node_air, "info_node_air");
LINK_ENTITY_TO_FUNC(info_null, "info_null");
LINK_ENTITY_TO_FUNC(info_player_deathmatch, "info_player_deathmatch");
LINK_ENTITY_TO_FUNC(info_player_start, "info_player_start");
LINK_ENTITY_TO_FUNC(info_target, "info_target");
LINK_ENTITY_TO_FUNC(info_teleport_destination, "info_teleport_destination");
LINK_ENTITY_TO_FUNC(infodecal, "infodecal");
LINK_ENTITY_TO_FUNC(item_airtank, "item_airtank");
LINK_ENTITY_TO_FUNC(item_antidote, "item_antidote");
LINK_ENTITY_TO_FUNC(item_battery, "item_battery");
LINK_ENTITY_TO_FUNC(item_healthkit, "item_healthkit");
LINK_ENTITY_TO_FUNC(item_longjump, "item_longjump");
LINK_ENTITY_TO_FUNC(item_security, "item_security");
LINK_ENTITY_TO_FUNC(item_sodacan, "item_sodacan");
LINK_ENTITY_TO_FUNC(item_suit, "item_suit");
LINK_ENTITY_TO_FUNC(laser_spot, "laser_spot");
LINK_ENTITY_TO_FUNC(light, "light");
LINK_ENTITY_TO_FUNC(light_environment, "light_environment");
LINK_ENTITY_TO_FUNC(light_spot, "light_spot");
LINK_ENTITY_TO_FUNC(momentary_door, "momentary_door");
LINK_ENTITY_TO_FUNC(momentary_rot_button, "momentary_rot_button");
LINK_ENTITY_TO_FUNC(monstermaker, "monstermaker");
LINK_ENTITY_TO_FUNC(monster_alien_controller, "monster_alien_controller");
LINK_ENTITY_TO_FUNC(monster_alien_grunt, "monster_alien_grunt");
LINK_ENTITY_TO_FUNC(monster_alien_slave, "monster_alien_slave");
LINK_ENTITY_TO_FUNC(monster_apache, "monster_apache");
LINK_ENTITY_TO_FUNC(monster_babycrab, "monster_babycrab");
LINK_ENTITY_TO_FUNC(monster_barnacle, "monster_barnacle");
LINK_ENTITY_TO_FUNC(monster_barney, "monster_barney");
LINK_ENTITY_TO_FUNC(monster_barney_dead, "monster_barney_dead");
LINK_ENTITY_TO_FUNC(monster_bigmomma, "monster_bigmomma");
LINK_ENTITY_TO_FUNC(monster_bloater, "monster_bloater");
LINK_ENTITY_TO_FUNC(monster_bullchicken, "monster_bullchicken");
LINK_ENTITY_TO_FUNC(monster_cine2_hvyweapons, "monster_cine2_hvyweapons");
LINK_ENTITY_TO_FUNC(monster_cine2_scientist, "monster_cine2_scientist");
LINK_ENTITY_TO_FUNC(monster_cine2_slave, "monster_cine2_slave");
LINK_ENTITY_TO_FUNC(monster_cine3_barney, "monster_cine3_barney");
LINK_ENTITY_TO_FUNC(monster_cine3_scientist, "monster_cine3_scientist");
LINK_ENTITY_TO_FUNC(monster_cine_barney, "monster_cine_barney");
LINK_ENTITY_TO_FUNC(monster_cine_panther, "monster_cine_panther");
LINK_ENTITY_TO_FUNC(monster_cine_scientist, "monster_cine_scientist");
LINK_ENTITY_TO_FUNC(monster_cockroach, "monster_cockroach");
LINK_ENTITY_TO_FUNC(monster_flyer, "monster_flyer");
LINK_ENTITY_TO_FUNC(monster_flyer_flock, "monster_flyer_flock");
LINK_ENTITY_TO_FUNC(monster_furniture, "monster_furniture");
LINK_ENTITY_TO_FUNC(monster_gargantua, "monster_gargantua");
LINK_ENTITY_TO_FUNC(monster_generic, "monster_generic");
LINK_ENTITY_TO_FUNC(monster_gman, "monster_gman");
LINK_ENTITY_TO_FUNC(monster_grunt_repel, "monster_grunt_repel");
LINK_ENTITY_TO_FUNC(monster_headcrab, "monster_headcrab");
LINK_ENTITY_TO_FUNC(monster_hevsuit_dead, "monster_hevsuit_dead");
LINK_ENTITY_TO_FUNC(monster_hgrunt_dead, "monster_hgrunt_dead");
LINK_ENTITY_TO_FUNC(monster_houndeye, "monster_houndeye");
LINK_ENTITY_TO_FUNC(monster_human_assassin, "monster_human_assassin");
LINK_ENTITY_TO_FUNC(monster_human_grunt, "monster_human_grunt");
LINK_ENTITY_TO_FUNC(monster_ichthyosaur, "monster_ichthyosaur");
LINK_ENTITY_TO_FUNC(monster_leech, "monster_leech");
LINK_ENTITY_TO_FUNC(monster_miniturret, "monster_miniturret");
LINK_ENTITY_TO_FUNC(monster_mortar, "monster_mortar");
LINK_ENTITY_TO_FUNC(monster_nihilanth, "monster_nihilanth");
LINK_ENTITY_TO_FUNC(monster_osprey, "monster_osprey");
LINK_ENTITY_TO_FUNC(monster_rat, "monster_rat");
LINK_ENTITY_TO_FUNC(monster_satchel, "monster_satchel");
LINK_ENTITY_TO_FUNC(monster_scientist, "monster_scientist");
LINK_ENTITY_TO_FUNC(monster_scientist_dead, "monster_scientist_dead");
LINK_ENTITY_TO_FUNC(monster_sentry, "monster_sentry");
LINK_ENTITY_TO_FUNC(monster_sitting_scientist, "monster_sitting_scientist");
LINK_ENTITY_TO_FUNC(monster_snark, "monster_snark");
LINK_ENTITY_TO_FUNC(monster_tentacle, "monster_tentacle");
LINK_ENTITY_TO_FUNC(monster_tentaclemaw, "monster_tentaclemaw");
LINK_ENTITY_TO_FUNC(monster_tripmine, "monster_tripmine");
LINK_ENTITY_TO_FUNC(monster_turret, "monster_turret");
LINK_ENTITY_TO_FUNC(monster_vortigaunt, "monster_vortigaunt");
LINK_ENTITY_TO_FUNC(monster_zombie, "monster_zombie");
LINK_ENTITY_TO_FUNC(multi_manager, "multi_manager");
LINK_ENTITY_TO_FUNC(multisource, "multisource");
LINK_ENTITY_TO_FUNC(nihilanth_energy_ball, "nihilanth_energy_ball");
LINK_ENTITY_TO_FUNC(node_viewer, "node_viewer");
LINK_ENTITY_TO_FUNC(node_viewer_fly, "node_viewer_fly");
LINK_ENTITY_TO_FUNC(node_viewer_human, "node_viewer_human");
LINK_ENTITY_TO_FUNC(node_viewer_large, "node_viewer_large");
LINK_ENTITY_TO_FUNC(path_corner, "path_corner");
LINK_ENTITY_TO_FUNC(path_track, "path_track");
LINK_ENTITY_TO_FUNC(player, "player");
LINK_ENTITY_TO_FUNC(player_loadsaved, "player_loadsaved");
LINK_ENTITY_TO_FUNC(player_weaponstrip, "player_weaponstrip");
LINK_ENTITY_TO_FUNC(rpg_rocket, "rpg_rocket");
LINK_ENTITY_TO_FUNC(scripted_sentence, "scripted_sentence");
LINK_ENTITY_TO_FUNC(scripted_sequence, "scripted_sequence");
LINK_ENTITY_TO_FUNC(soundent, "soundent");
LINK_ENTITY_TO_FUNC(spark_shower, "spark_shower");
LINK_ENTITY_TO_FUNC(speaker, "speaker");
LINK_ENTITY_TO_FUNC(squidspit, "squidspit");
LINK_ENTITY_TO_FUNC(streak_spiral, "streak_spiral");
LINK_ENTITY_TO_FUNC(target_cdaudio, "target_cdaudio");
LINK_ENTITY_TO_FUNC(test_effect, "test_effect");
LINK_ENTITY_TO_FUNC(testhull, "testhull");
LINK_ENTITY_TO_FUNC(trigger, "trigger");
LINK_ENTITY_TO_FUNC(trigger_auto, "trigger_auto");
LINK_ENTITY_TO_FUNC(trigger_autosave, "trigger_autosave");
LINK_ENTITY_TO_FUNC(trigger_camera, "trigger_camera");
LINK_ENTITY_TO_FUNC(trigger_cdaudio, "trigger_cdaudio");
LINK_ENTITY_TO_FUNC(trigger_changelevel, "trigger_changelevel");
LINK_ENTITY_TO_FUNC(trigger_changetarget, "trigger_changetarget");
LINK_ENTITY_TO_FUNC(trigger_counter, "trigger_counter");
LINK_ENTITY_TO_FUNC(trigger_endsection, "trigger_endsection");
LINK_ENTITY_TO_FUNC(trigger_gravity, "trigger_gravity");
LINK_ENTITY_TO_FUNC(trigger_hurt, "trigger_hurt");
LINK_ENTITY_TO_FUNC(trigger_monsterjump, "trigger_monsterjump");
LINK_ENTITY_TO_FUNC(trigger_multiple, "trigger_multiple");
LINK_ENTITY_TO_FUNC(trigger_once, "trigger_once");
LINK_ENTITY_TO_FUNC(trigger_push, "trigger_push");
LINK_ENTITY_TO_FUNC(trigger_relay, "trigger_relay");
LINK_ENTITY_TO_FUNC(trigger_teleport, "trigger_teleport");
LINK_ENTITY_TO_FUNC(trigger_transition, "trigger_transition");
LINK_ENTITY_TO_FUNC(weapon_357, "weapon_357");
LINK_ENTITY_TO_FUNC(weapon_9mmAR, "weapon_9mmAR");
LINK_ENTITY_TO_FUNC(weapon_9mmhandgun, "weapon_9mmhandgun");
LINK_ENTITY_TO_FUNC(weapon_crossbow, "weapon_crossbow");
LINK_ENTITY_TO_FUNC(weapon_crowbar, "weapon_crowbar");
LINK_ENTITY_TO_FUNC(weapon_egon, "weapon_egon");
LINK_ENTITY_TO_FUNC(weapon_gauss, "weapon_gauss");
LINK_ENTITY_TO_FUNC(weapon_glock, "weapon_glock");
LINK_ENTITY_TO_FUNC(weapon_handgrenade, "weapon_handgrenade");
LINK_ENTITY_TO_FUNC(weapon_hornetgun, "weapon_hornetgun");
LINK_ENTITY_TO_FUNC(weapon_mp5, "weapon_mp5");
LINK_ENTITY_TO_FUNC(weapon_python, "weapon_python");
LINK_ENTITY_TO_FUNC(weapon_rpg, "weapon_rpg");
LINK_ENTITY_TO_FUNC(weapon_satchel, "weapon_satchel");
LINK_ENTITY_TO_FUNC(weapon_shotgun, "weapon_shotgun");
LINK_ENTITY_TO_FUNC(weapon_snark, "weapon_snark");
LINK_ENTITY_TO_FUNC(weapon_tripmine, "weapon_tripmine");
LINK_ENTITY_TO_FUNC(weaponbox, "weaponbox");
LINK_ENTITY_TO_FUNC(world_items, "world_items");
LINK_ENTITY_TO_FUNC(worldspawn, "worldspawn");
LINK_ENTITY_TO_FUNC(xen_hair, "xen_hair");
LINK_ENTITY_TO_FUNC(xen_hull, "xen_hull");
LINK_ENTITY_TO_FUNC(xen_plantlight, "xen_plantlight");
LINK_ENTITY_TO_FUNC(xen_spore_large, "xen_spore_large");
LINK_ENTITY_TO_FUNC(xen_spore_medium, "xen_spore_medium");
LINK_ENTITY_TO_FUNC(xen_spore_small, "xen_spore_small");
LINK_ENTITY_TO_FUNC(xen_tree, "xen_tree");
LINK_ENTITY_TO_FUNC(xen_ttrigger, "xen_ttrigger");

// entities for Team Fortress 1.5
LINK_ENTITY_TO_FUNC(building_dispenser, "building_dispenser");
LINK_ENTITY_TO_FUNC(building_sentrygun, "building_sentrygun");
LINK_ENTITY_TO_FUNC(building_sentrygun_base, "building_sentrygun_base");
LINK_ENTITY_TO_FUNC(detpack, "detpack");
LINK_ENTITY_TO_FUNC(dispenser_refill_timer, "dispenser_refill_timer");
LINK_ENTITY_TO_FUNC(func_nobuild, "func_nobuild");
LINK_ENTITY_TO_FUNC(ghost, "ghost");
LINK_ENTITY_TO_FUNC(info_player_teamspawn, "info_player_teamspawn");
LINK_ENTITY_TO_FUNC(info_tfdetect, "info_tfdetect");
LINK_ENTITY_TO_FUNC(info_tfgoal, "info_tfgoal");
LINK_ENTITY_TO_FUNC(info_tfgoal_timer, "info_tfgoal_timer");
LINK_ENTITY_TO_FUNC(item_armor1, "item_armor1");
LINK_ENTITY_TO_FUNC(item_armor2, "item_armor2");
LINK_ENTITY_TO_FUNC(item_armor3, "item_armor3");
LINK_ENTITY_TO_FUNC(item_artifact_envirosuit, "item_artifact_envirosuit");
LINK_ENTITY_TO_FUNC(item_artifact_invisibility, "item_artifact_invisibility");
LINK_ENTITY_TO_FUNC(item_artifact_invulnerability, "item_artifact_invulnerability");
LINK_ENTITY_TO_FUNC(item_artifact_super_damage, "item_artifact_super_damage");
LINK_ENTITY_TO_FUNC(item_cells, "item_cells");
LINK_ENTITY_TO_FUNC(item_health, "item_health");
LINK_ENTITY_TO_FUNC(item_rockets, "item_rockets");
LINK_ENTITY_TO_FUNC(item_shells, "item_shells");
LINK_ENTITY_TO_FUNC(item_spikes, "item_spikes");
LINK_ENTITY_TO_FUNC(item_tfgoal, "item_tfgoal");
LINK_ENTITY_TO_FUNC(i_p_t, "i_p_t");
LINK_ENTITY_TO_FUNC(i_t_g, "i_t_g");
LINK_ENTITY_TO_FUNC(i_t_t, "i_t_t");
LINK_ENTITY_TO_FUNC(teledeath, "teledeath");
LINK_ENTITY_TO_FUNC(tf_ammo_rpgclip, "tf_ammo_rpgclip");
LINK_ENTITY_TO_FUNC(tf_flame, "tf_flame");
LINK_ENTITY_TO_FUNC(tf_flamethrower_burst, "tf_flamethrower_burst");
LINK_ENTITY_TO_FUNC(tf_gl_grenade, "tf_gl_grenade");
LINK_ENTITY_TO_FUNC(tf_ic_rocket, "tf_ic_rocket");
LINK_ENTITY_TO_FUNC(tf_nailgun_nail, "tf_nailgun_nail");
LINK_ENTITY_TO_FUNC(tf_rpg_rocket, "tf_rpg_rocket");
LINK_ENTITY_TO_FUNC(tf_weapon_ac, "tf_weapon_ac");
LINK_ENTITY_TO_FUNC(tf_weapon_autorifle, "tf_weapon_autorifle");
LINK_ENTITY_TO_FUNC(tf_weapon_axe, "tf_weapon_axe");
LINK_ENTITY_TO_FUNC(tf_weapon_caltrop, "tf_weapon_caltrop");
LINK_ENTITY_TO_FUNC(tf_weapon_caltropgrenade, "tf_weapon_caltropgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_concussiongrenade, "tf_weapon_concussiongrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_empgrenade, "tf_weapon_empgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_flamethrower, "tf_weapon_flamethrower");
LINK_ENTITY_TO_FUNC(tf_weapon_gasgrenade, "tf_weapon_gasgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_genericprimedgrenade, "tf_weapon_genericprimedgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_gl, "tf_weapon_gl");
LINK_ENTITY_TO_FUNC(tf_weapon_ic, "tf_weapon_ic");
LINK_ENTITY_TO_FUNC(tf_weapon_knife, "tf_weapon_knife");
LINK_ENTITY_TO_FUNC(tf_weapon_medikit, "tf_weapon_medikit");
LINK_ENTITY_TO_FUNC(tf_weapon_mirvbomblet, "tf_weapon_mirvbomblet");
LINK_ENTITY_TO_FUNC(tf_weapon_mirvgrenade, "tf_weapon_mirvgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_nailgrenade, "tf_weapon_nailgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_napalmgrenade, "tf_weapon_napalmgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_ng, "tf_weapon_ng");
LINK_ENTITY_TO_FUNC(tf_weapon_normalgrenade, "tf_weapon_normalgrenade");
LINK_ENTITY_TO_FUNC(tf_weapon_pl, "tf_weapon_pl");
LINK_ENTITY_TO_FUNC(tf_weapon_railgun, "tf_weapon_railgun");
LINK_ENTITY_TO_FUNC(tf_weapon_rpg, "tf_weapon_rpg");
LINK_ENTITY_TO_FUNC(tf_weapon_shotgun, "tf_weapon_shotgun");
LINK_ENTITY_TO_FUNC(tf_weapon_sniperrifle, "tf_weapon_sniperrifle");
LINK_ENTITY_TO_FUNC(tf_weapon_spanner, "tf_weapon_spanner");
LINK_ENTITY_TO_FUNC(tf_weapon_superng, "tf_weapon_superng");
LINK_ENTITY_TO_FUNC(tf_weapon_supershotgun, "tf_weapon_supershotgun");
LINK_ENTITY_TO_FUNC(tf_weapon_tranq, "tf_weapon_tranq");
LINK_ENTITY_TO_FUNC(timer, "timer");

// entities for Counter-Strike (Beta 6.5, 6.6, 7.0, 7.1, Release 1.0, 1.1 )
LINK_ENTITY_TO_FUNC(ammo_338magnum, "ammo_338magnum");
LINK_ENTITY_TO_FUNC(ammo_357sig, "ammo_357sig");
LINK_ENTITY_TO_FUNC(ammo_45acp, "ammo_45acp");
LINK_ENTITY_TO_FUNC(ammo_50ae, "ammo_50ae");
LINK_ENTITY_TO_FUNC(ammo_556nato, "ammo_556nato");
LINK_ENTITY_TO_FUNC(ammo_556natobox, "ammo_556natobox");
LINK_ENTITY_TO_FUNC(ammo_57mm, "ammo_57mm");
LINK_ENTITY_TO_FUNC(ammo_762nato, "ammo_762nato");
LINK_ENTITY_TO_FUNC(ammo_9mm, "ammo_9mm");
LINK_ENTITY_TO_FUNC(armoury_entity, "armoury_entity");
LINK_ENTITY_TO_FUNC(env_bombglow, "env_bombglow");
LINK_ENTITY_TO_FUNC(func_bomb_target, "func_bomb_target");
LINK_ENTITY_TO_FUNC(func_buyzone, "func_buyzone");
LINK_ENTITY_TO_FUNC(func_escapezone, "func_escapezone");
LINK_ENTITY_TO_FUNC(func_grencatch, "func_grencatch");
LINK_ENTITY_TO_FUNC(func_hostage_rescue, "func_hostage_rescue");
LINK_ENTITY_TO_FUNC(func_vehicle, "func_vehicle");
LINK_ENTITY_TO_FUNC(func_vehiclecontrols, "func_vehiclecontrols");
LINK_ENTITY_TO_FUNC(func_vip_safetyzone, "func_vip_safetyzone");
LINK_ENTITY_TO_FUNC(func_weaponcheck, "func_weaponcheck");
LINK_ENTITY_TO_FUNC(hostage_entity, "hostage_entity");
LINK_ENTITY_TO_FUNC(info_bomb_target, "info_bomb_target");
LINK_ENTITY_TO_FUNC(info_hostage_rescue, "info_hostage_rescue");
LINK_ENTITY_TO_FUNC(info_map_parameters, "info_map_parameters");
LINK_ENTITY_TO_FUNC(info_vip_start, "info_vip_start");
LINK_ENTITY_TO_FUNC(item_assaultsuit, "item_assaultsuit");
LINK_ENTITY_TO_FUNC(item_kevlar, "item_kevlar");
LINK_ENTITY_TO_FUNC(item_thighpack, "item_thighpack");
LINK_ENTITY_TO_FUNC(weapon_ak47, "weapon_ak47");
LINK_ENTITY_TO_FUNC(weapon_aug, "weapon_aug");
LINK_ENTITY_TO_FUNC(weapon_awp, "weapon_awp");
LINK_ENTITY_TO_FUNC(weapon_c4, "weapon_c4");
LINK_ENTITY_TO_FUNC(weapon_deagle, "weapon_deagle");
LINK_ENTITY_TO_FUNC(weapon_elite, "weapon_elite");
LINK_ENTITY_TO_FUNC(weapon_fiveseven, "weapon_fiveseven");
LINK_ENTITY_TO_FUNC(weapon_flashbang, "weapon_flashbang");
LINK_ENTITY_TO_FUNC(weapon_g3sg1, "weapon_g3sg1");
LINK_ENTITY_TO_FUNC(weapon_glock18, "weapon_glock18");
LINK_ENTITY_TO_FUNC(weapon_hegrenade, "weapon_hegrenade");
LINK_ENTITY_TO_FUNC(weapon_knife, "weapon_knife");
LINK_ENTITY_TO_FUNC(weapon_m249, "weapon_m249");
LINK_ENTITY_TO_FUNC(weapon_m3, "weapon_m3");
LINK_ENTITY_TO_FUNC(weapon_m4a1, "weapon_m4a1");
LINK_ENTITY_TO_FUNC(weapon_mac10, "weapon_mac10");
LINK_ENTITY_TO_FUNC(weapon_mp5navy, "weapon_mp5navy");
LINK_ENTITY_TO_FUNC(weapon_p228, "weapon_p228");
LINK_ENTITY_TO_FUNC(weapon_p90, "weapon_p90");
LINK_ENTITY_TO_FUNC(weapon_scout, "weapon_scout");
LINK_ENTITY_TO_FUNC(weapon_sg550, "weapon_sg550");
LINK_ENTITY_TO_FUNC(weapon_sg552, "weapon_sg552");
LINK_ENTITY_TO_FUNC(weapon_smokegrenade, "weapon_smokegrenade");
LINK_ENTITY_TO_FUNC(weapon_tmp, "weapon_tmp");
LINK_ENTITY_TO_FUNC(weapon_ump45, "weapon_ump45");
LINK_ENTITY_TO_FUNC(weapon_usp, "weapon_usp");
LINK_ENTITY_TO_FUNC(weapon_xm1014, "weapon_xm1014");

// entities for HolyWars (Beta 1.0)
LINK_ENTITY_TO_FUNC( ammo_doubleshotgun, "ammo_doubleshotgun" );
LINK_ENTITY_TO_FUNC( ammo_machinegun, "ammo_machinegun" );
LINK_ENTITY_TO_FUNC( ammo_railgun, "ammo_railgun" );
LINK_ENTITY_TO_FUNC( ammo_rocketlauncher, "ammo_rocketlauncher" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_available, "event_trigger_halo_available" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_existing, "event_trigger_halo_existing" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_not_available, "event_trigger_halo_not_available" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_not_existing, "event_trigger_halo_not_existing" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_not_owned, "event_trigger_halo_not_owned" );
LINK_ENTITY_TO_FUNC( event_trigger_halo_owned, "event_trigger_halo_owned" );
LINK_ENTITY_TO_FUNC( halo, "halo" );
LINK_ENTITY_TO_FUNC( halo_base, "halo_base" );
LINK_ENTITY_TO_FUNC( holywars_rocket, "holywars_rocket" );
LINK_ENTITY_TO_FUNC( info_jumppad_target, "info_jumppad_target" );
LINK_ENTITY_TO_FUNC( jumppad_sign, "jumppad_sign" );
LINK_ENTITY_TO_FUNC( trigger_jumppad, "trigger_jumppad" );
LINK_ENTITY_TO_FUNC( weapon_doubleshotgun, "weapon_doubleshotgun" );
LINK_ENTITY_TO_FUNC( weapon_jackhammer, "weapon_jackhammer" );
LINK_ENTITY_TO_FUNC( weapon_machinegun, "weapon_machinegun" );
LINK_ENTITY_TO_FUNC( weapon_railgun, "weapon_railgun" );
LINK_ENTITY_TO_FUNC( weapon_rocketlauncher, "weapon_rocketlauncher" );

// entities for DMC
//LINK_ENTITY_TO_FUNC( item_armor1, "item_armor1" );
//LINK_ENTITY_TO_FUNC( item_armor2, "item_armor2" );
//LINK_ENTITY_TO_FUNC( item_armor3, "item_armor3" );
LINK_ENTITY_TO_FUNC( item_armorInv, "item_armorInv" );
//LINK_ENTITY_TO_FUNC( item_artifact_envirosuit, "item_artifact_envirosuit" );
//LINK_ENTITY_TO_FUNC( item_artifact_invisibility, "item_artifact_invisibility" );
//LINK_ENTITY_TO_FUNC( item_artifact_invulnerability, "item_artifact_invulnerability" );
//LINK_ENTITY_TO_FUNC( item_artifact_super_damage, "item_artifact_super_damage" );
LINK_ENTITY_TO_FUNC( item_backpack, "item_backpack" );
//LINK_ENTITY_TO_FUNC( item_cells, "item_cells" );
//LINK_ENTITY_TO_FUNC( item_health, "item_health" );
//LINK_ENTITY_TO_FUNC( item_rockets, "item_rockets" );
//LINK_ENTITY_TO_FUNC( item_shells, "item_shells" );
//LINK_ENTITY_TO_FUNC( item_spikes, "item_spikes" );
LINK_ENTITY_TO_FUNC( item_weapon, "item_weapon" );
LINK_ENTITY_TO_FUNC( quake_nail, "quake_nail" );
LINK_ENTITY_TO_FUNC( quake_rocket, "quake_rocket" );
//LINK_ENTITY_TO_FUNC( teledeath, "teledeath" );
LINK_ENTITY_TO_FUNC( weapon_grenadelauncher, "weapon_grenadelauncher" );
LINK_ENTITY_TO_FUNC( weapon_lightning, "weapon_lightning" );
LINK_ENTITY_TO_FUNC( weapon_nailgun, "weapon_nailgun" );
LINK_ENTITY_TO_FUNC( weapon_quakegun, "weapon_quakegun" );
//LINK_ENTITY_TO_FUNC( weapon_rocketlauncher, "weapon_rocketlauncher" );
LINK_ENTITY_TO_FUNC( weapon_supernailgun, "weapon_supernailgun" );
LINK_ENTITY_TO_FUNC( weapon_supershotgun, "weapon_supershotgun" );

// entities for Opposing Force
LINK_ENTITY_TO_FUNC( ammo_556, "ammo_556" );
LINK_ENTITY_TO_FUNC( ammo_762, "ammo_762" );
LINK_ENTITY_TO_FUNC( ammo_eagleclip, "ammo_eagleclip" );
LINK_ENTITY_TO_FUNC( ammo_spore, "ammo_spore" );
LINK_ENTITY_TO_FUNC( charged_bolt, "charged_bolt" );
LINK_ENTITY_TO_FUNC( displacer_ball, "displacer_ball" );
LINK_ENTITY_TO_FUNC( eagle_laser, "eagle_laser" );
LINK_ENTITY_TO_FUNC( env_blowercannon, "env_blowercannon" );
LINK_ENTITY_TO_FUNC( env_electrified_wire, "env_electrified_wire" );
LINK_ENTITY_TO_FUNC( env_genewormcloud, "env_genewormcloud" );
LINK_ENTITY_TO_FUNC( env_genewormspawn, "env_genewormspawn" );
LINK_ENTITY_TO_FUNC( env_rope, "env_rope" );
LINK_ENTITY_TO_FUNC( env_spritetrain, "env_spritetrain" );
LINK_ENTITY_TO_FUNC( func_op4mortarcontroller, "func_op4mortarcontroller" );
LINK_ENTITY_TO_FUNC( func_tank_of, "func_tank_of" );
LINK_ENTITY_TO_FUNC( func_tankcontrols_of, "func_tankcontrols_of" );
LINK_ENTITY_TO_FUNC( func_tanklaser_of, "func_tanklaser_of" );
LINK_ENTITY_TO_FUNC( func_tankmortar_of, "func_tankmortar_of" );
LINK_ENTITY_TO_FUNC( func_tankrocket_of, "func_tankrocket_of" );
LINK_ENTITY_TO_FUNC( gonomeguts, "gonomeguts" );
LINK_ENTITY_TO_FUNC( grapple_tip, "grapple_tip" );
LINK_ENTITY_TO_FUNC( hvr_blkop_rocket, "hvr_blkop_rocket" );
LINK_ENTITY_TO_FUNC( info_ctfdetect, "info_ctfdetect" );
LINK_ENTITY_TO_FUNC( info_ctfspawn, "info_ctfspawn" );
LINK_ENTITY_TO_FUNC( info_ctfspawn_powerup, "info_ctfspawn_powerup" );
LINK_ENTITY_TO_FUNC( info_displacer_earth_target, "info_displacer_earth_target" );
LINK_ENTITY_TO_FUNC( info_displacer_xen_target, "info_displacer_xen_target" );
LINK_ENTITY_TO_FUNC( info_pitworm, "info_pitworm" );
LINK_ENTITY_TO_FUNC( info_pitworm_steam_lock, "info_pitworm_steam_lock" );
LINK_ENTITY_TO_FUNC( item_ctfaccelerator, "item_ctfaccelerator" );
LINK_ENTITY_TO_FUNC( item_ctfbackpack, "item_ctfbackpack" );
LINK_ENTITY_TO_FUNC( item_ctfbase, "item_ctfbase" );
LINK_ENTITY_TO_FUNC( item_ctfflag, "item_ctfflag" );
LINK_ENTITY_TO_FUNC( item_ctflongjump, "item_ctflongjump" );
LINK_ENTITY_TO_FUNC( item_ctfportablehev, "item_ctfportablehev" );
LINK_ENTITY_TO_FUNC( item_ctfregeneration, "item_ctfregeneration" );
LINK_ENTITY_TO_FUNC( item_generic, "item_generic" );
LINK_ENTITY_TO_FUNC( item_nuclearbomb, "item_nuclearbomb" );
LINK_ENTITY_TO_FUNC( item_nuclearbombbutton, "item_nuclearbombbutton" );
LINK_ENTITY_TO_FUNC( item_nuclearbombtimer, "item_nuclearbombtimer" );
LINK_ENTITY_TO_FUNC( item_vest, "item_vest" );
LINK_ENTITY_TO_FUNC( monster_ShockTrooper_dead, "monster_ShockTrooper_dead" );
LINK_ENTITY_TO_FUNC( monster_alien_babyvoltigore, "monster_alien_babyvoltigore" );
LINK_ENTITY_TO_FUNC( monster_alien_slave_dead, "monster_alien_slave_dead" );
LINK_ENTITY_TO_FUNC( monster_alien_voltigore, "monster_alien_voltigore" );
LINK_ENTITY_TO_FUNC( monster_assassin_repel, "monster_assassin_repel" );
LINK_ENTITY_TO_FUNC( monster_blkop_apache, "monster_blkop_apache" );
LINK_ENTITY_TO_FUNC( monster_blkop_osprey, "monster_blkop_osprey" );
LINK_ENTITY_TO_FUNC( monster_cleansuit_scientist, "monster_cleansuit_scientist" );
LINK_ENTITY_TO_FUNC( monster_cleansuit_scientist_dead, "monster_cleansuit_scientist_dead" );
LINK_ENTITY_TO_FUNC( monster_drillsergeant, "monster_drillsergeant" );
LINK_ENTITY_TO_FUNC( monster_fgrunt_repel, "monster_fgrunt_repel" );
LINK_ENTITY_TO_FUNC( monster_geneworm, "monster_geneworm" );
LINK_ENTITY_TO_FUNC( monster_gonome, "monster_gonome" );
LINK_ENTITY_TO_FUNC( monster_gonome_dead, "monster_gonome_dead" );
LINK_ENTITY_TO_FUNC( monster_grunt_ally_repel, "monster_grunt_ally_repel" );
LINK_ENTITY_TO_FUNC( monster_hfgrunt_dead, "monster_hfgrunt_dead" );
LINK_ENTITY_TO_FUNC( monster_houndeye_dead, "monster_houndeye_dead" );
LINK_ENTITY_TO_FUNC( monster_human_friendly_grunt, "monster_human_friendly_grunt" );
LINK_ENTITY_TO_FUNC( monster_human_grunt_ally, "monster_human_grunt_ally" );
LINK_ENTITY_TO_FUNC( monster_human_grunt_ally_dead, "monster_human_grunt_ally_dead" );
LINK_ENTITY_TO_FUNC( monster_human_medic_ally, "monster_human_medic_ally" );
LINK_ENTITY_TO_FUNC( monster_human_torch_ally, "monster_human_torch_ally" );
LINK_ENTITY_TO_FUNC( monster_male_assassin, "monster_male_assassin" );
LINK_ENTITY_TO_FUNC( monster_massassin_dead, "monster_massassin_dead" );
LINK_ENTITY_TO_FUNC( monster_medic_ally_repel, "monster_medic_ally_repel" );
LINK_ENTITY_TO_FUNC( monster_op4loader, "monster_op4loader" );
LINK_ENTITY_TO_FUNC( monster_otis, "monster_otis" );
LINK_ENTITY_TO_FUNC( monster_otis_dead, "monster_otis_dead" );
LINK_ENTITY_TO_FUNC( monster_penguin, "monster_penguin" );
LINK_ENTITY_TO_FUNC( monster_pitdrone, "monster_pitdrone" );
LINK_ENTITY_TO_FUNC( monster_pitworm, "monster_pitworm" );
LINK_ENTITY_TO_FUNC( monster_pitworm_up, "monster_pitworm_up" );
LINK_ENTITY_TO_FUNC( monster_recruit, "monster_recruit" );
LINK_ENTITY_TO_FUNC( monster_shockroach, "monster_shockroach" );
LINK_ENTITY_TO_FUNC( monster_shocktrooper, "monster_shocktrooper" );
LINK_ENTITY_TO_FUNC( monster_shocktrooper_repel, "monster_shocktrooper_repel" );
LINK_ENTITY_TO_FUNC( monster_sitting_cleansuit_scientist, "monster_sitting_cleansuit_scientist" );
LINK_ENTITY_TO_FUNC( monster_skeleton_dead, "monster_skeleton_dead" );
LINK_ENTITY_TO_FUNC( monster_torch_ally_repel, "monster_torch_ally_repel" );
LINK_ENTITY_TO_FUNC( monster_zombie_barney, "monster_zombie_barney" );
LINK_ENTITY_TO_FUNC( monster_zombie_soldier, "monster_zombie_soldier" );
LINK_ENTITY_TO_FUNC( monster_zombie_soldier_dead, "monster_zombie_soldier_dead" );
LINK_ENTITY_TO_FUNC( mortar_shell, "mortar_shell" );
LINK_ENTITY_TO_FUNC( op4mortar, "op4mortar" );
LINK_ENTITY_TO_FUNC( pitdronespike, "pitdronespike" );
LINK_ENTITY_TO_FUNC( pitworm_gib, "pitworm_gib" );
LINK_ENTITY_TO_FUNC( pitworm_gibshooter, "pitworm_gibshooter" );
LINK_ENTITY_TO_FUNC( rope_sample, "rope_sample" );
LINK_ENTITY_TO_FUNC( rope_segment, "rope_segment" );
LINK_ENTITY_TO_FUNC( shock_beam, "shock_beam" );
LINK_ENTITY_TO_FUNC( spore, "spore" );
LINK_ENTITY_TO_FUNC( trigger_ctfgeneric, "trigger_ctfgeneric" );
LINK_ENTITY_TO_FUNC( trigger_geneworm_hit, "trigger_geneworm_hit" );
LINK_ENTITY_TO_FUNC( trigger_kill_nogib, "trigger_kill_nogib" );
LINK_ENTITY_TO_FUNC( trigger_playerfreeze, "trigger_playerfreeze" );
LINK_ENTITY_TO_FUNC( trigger_xen_return, "trigger_xen_return" );
LINK_ENTITY_TO_FUNC( weapon_displacer, "weapon_displacer" );
LINK_ENTITY_TO_FUNC( weapon_eagle, "weapon_eagle" );
LINK_ENTITY_TO_FUNC( weapon_grapple, "weapon_grapple" );
LINK_ENTITY_TO_FUNC( weapon_penguin, "weapon_penguin" );
LINK_ENTITY_TO_FUNC( weapon_pipewrench, "weapon_pipewrench" );
LINK_ENTITY_TO_FUNC( weapon_shockrifle, "weapon_shockrifle" );
LINK_ENTITY_TO_FUNC( weapon_shockroach, "weapon_shockroach" );
LINK_ENTITY_TO_FUNC( weapon_sniperrifle, "weapon_sniperrifle" );
LINK_ENTITY_TO_FUNC( weapon_sporelauncher, "weapon_sporelauncher" );
