#pragma once
#if !defined(SDK_DEFINES_H)
#define SDK_DEFINES_H
enum {
	FL_FLY =		BIT(0),
	FL_SWIM =		BIT(1),
	FL_CONVEYOR =		BIT(2),
	FL_CLIENT =		BIT(3),
	FL_INWATER =		BIT(4),
	FL_MONSTER =		BIT(5),
	FL_GODMODE =		BIT(6),
	FL_NOTARGET =		BIT(7),
	FL_SKIPLOCALHOST =	BIT(8),
	FL_ONGROUND =		BIT(9),
	FL_PARTIALGROUND =	BIT(10),
	FL_WATERJUMP =		BIT(11),
	FL_FROZEN =		BIT(12),
	FL_FAKECLIENT =		BIT(13),
	FL_DUCKING =		BIT(14),
	FL_FLOAT =		BIT(15),
	FL_GRAPHED =		BIT(16),
};

enum {
	DAMAGE_NO,
	DAMAGE_YES,
	DAMAGE_AIM
};

enum {
	MOVETYPE_NONE = 0,
	MOVETYPE_WALK = 3,
	MOVETYPE_STEP,
	MOVETYPE_FLY,
	MOVETYPE_TOSS,
	MOVETYPE_PUSH,
	MOVETYPE_NOCLIP,
	MOVETYPE_FLYMISSILE,
	MOVETYPE_BOUNCE,
	MOVETYPE_BOUNCEMISSILE,
	MOVETYPE_FOLLOW,
	MOVETYPE_PUSHSTEP,
// xash3d extension
	MOVETYPE_COMPOUND
};

enum {
	SOLID_NOT,
	SOLID_TRIGGER,
	SOLID_BBOX,
	SOLID_SLIDEBOX,
	SOLID_BSP,
// xash3d extension
	SOLID_CUSTOM
};

enum {
	DEAD_NO,
	DEAD_DYING,
	DEAD_DEAD,
	DEAD_RESPAWNABLE
};

enum {
	EF_BRIGHTFIELD =	BIT(0),
	EF_MUZZLEFLASH =	BIT(1),
	EF_BRIGHTLIGHT =	BIT(2),
	EF_DIMLIGHT =		BIT(3),
	EF_NODRAW =		BIT(7)
};

enum {
	MSG_BROADCAST,
	MSG_ONE,
	MSG_ALL,
	MSG_INIT
};

enum {
	CVAR_ARCHIVE =		BIT(0),
	CVAR_USERINFO =		BIT(1),
	CVAR_SERVERINFO =	BIT(2)
};

enum {
	CONTENTS_LADDER = -16,
	CONTENTS_TRANSLUC,
	CONTENTS_CURR_DOWN,
	CONTENTS_CURR_UP,
	CONTENTS_CURR_270,
	CONTENTS_CURR_180,
	CONTENTS_CURR_90,
	CONTENTS_CURR_0,
	CONTENTS_CLIP,
	CONTENTS_ORIGIN,
	CONTENTS_SKY,
	CONTENTS_LAVA,
	CONTENTS_SLIME,
	CONTENTS_WATER,
	CONTENTS_SOLID,
	CONTENTS_EMPTY
};

enum { // channels
	CHAN_AUTO,
	CHAN_WEAPON,
	CHAN_VOICE,
	CHAN_ITEM,
	CHAN_BODY
};

// attenuation values
#define ATTN_NONE	0.0f
#define ATTN_NORM	0.8f
#define ATTN_IDLE	2.0f
#define ATTN_STATIC	1.25f

enum {
	ACTION_ATTACK1 =	BIT(0),
	ACTION_JUMP =		BIT(1),
	ACTION_CROUCH =		BIT(2),
	ACTION_MOVEFORWARD =	BIT(3),
	ACTION_MOVEBACK =	BIT(4),
	ACTION_USE =		BIT(5),
	ACTION_MOVELEFT =	BIT(9),
	ACTION_MOVERIGHT =	BIT(10),
	ACTION_ATTACK2 =	BIT(11),
	ACTION_RUN =		BIT(12),
	ACTION_RELOAD =		BIT(13)
};

enum {
	STATE_TOP,
	STATE_BOTTOM,
	STATE_UP,
	STATE_DOWN
};

enum {
	SVC_TEMP_ENTITY =	23,
	SVC_INTERMISSION =	30,
	SVC_CDTRACK =		32
};

enum {
	RF_GLOW =	19
};
#endif // SDK_DEFINES_H
